export const ERROR_CODES = {
  NOT_FOUND: 'BFF-404',
  BAD_REQUEST: 'BFF-400',
  BAD_CONFIGURATION: 'BFF-000',
  RESPONSE_VALIDATION_ERROR: 'BFF-421',
  PROVIDER_ERROR: 'BFF-001',
  INTERNAL_SERVER_ERROR: 'BFF-500',
} as const;
