name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - run: pnpm install --frozen-lockfile
      # Test needs to run before build, because there are
      # some tests that deleted the dist folder
      - run: pnpm test:ci
      - run: pnpm build
      - run: pnpm publish -r --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
